POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlYW5wYXJrQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjA5OTg5MDZ9.WbmZUQ6efHcUCWJDcWZf6ZeFN2fUiILIdhOVl9kJlPE

{
    "title": "Forget NFTs. GameStop Is Going About Business ‘the Old Fashion Way.’",
    "author": "Emily Dattilo",
    "url" : "https://www.barrons.com/articles/gamestop-stock-price-earnings-report-2be262a2",
    "likes": 0
}